[package]
name = "laterna"
version = "0.1.0"
edition = "2021"
description = "Render piano rolls to the terminal using block characters."

[[bin]]
name = "laterna"
path = "laterna-cli.rs"

[lib]
path = "laterna.rs"

[dependencies]
thatsit = { git = "https://github.com/egasimus/thatsit" }
